name: lsa_calendar_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+1

environment:
  sdk: ^3.8.1

dependencies:  
  google_sign_in: ^6.2.2
  font_awesome_flutter: ^10.7.0
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.0.0
  http: ^0.13.5
  shared_preferences: ^2.3.0

  flutter:
    sdk: flutter  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:  
  color: "#e7d9be"   
  image: assets/images/splash_base.png    
  # fullscreen: true
  
  android_12:
    image: assets/images/splash_android12.png
    color: "#e7d9be"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#c0b691"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.testing
    - .env.production
    - assets/images/
